{% set version = "2.8.0" %}

package:
  name: pulp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PuLP/PuLP-{{ version }}.tar.gz
  sha256: 4903bf96110bbab8ed2c68533f90565ebb76aa367d9e4df38e51bf727927c125
  patches:
    # Use the conda provided cbc binary, not those bundled in tar-ball:
    - pulp.cfg.linux.patch
    - pulp.cfg.osx.patch

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv
    # Remove bundled cbc binaries, using coin-or-cbc provided cbc instead:
    - rm -rf "${SP_DIR}/pulp/solverdir/cbc"
    - rm "${SP_DIR}/pulp/solverdir/CoinMP.dll"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - amply >=0.1.2
    - coin-or-cbc
    - python

test:
  imports:
    - pulp
    - pulp.solverdir
  commands:
    - pip check
    - python -c "import pulp; assert pulp.LpSolverDefault, 'default solver not available'"
  requires:
    - pip

about:
  summary: |
    PuLP is an LP modeler written in python. PuLP can generate MPS or LP files
    and call GLPK, COIN CLP/CBC, CPLEX, and GUROBI to solve linear problems.
  home: https://github.com/coin-or/pulp
  license: MIT
  license_file: LICENSE
  doc_url: https://pythonhosted.org/PuLP/
  dev_url: https://github.com/coin-or/pulp
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - christopher-schroeder
    - venaturum
