{% set version = "2.6.0" %}

package:
  name: pulp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PuLP/PuLP-{{ version }}.tar.gz
  sha256: 4b4f7e1e954453e1b233720be23aea2f10ff068a835ac10c090a93d8e2eb2e8d

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv
    - rm "${SP_DIR}/pulp/solverdir/CoinMP.dll"  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - amply >=0.1.2
    # We use glpk on Windows because coincbc is only packaged on Unix, currently.
    - coincbc  # [not win]
    - glpk  # [win]
    - python

test:
  imports:
    - pulp
    - pulp.solverdir
  commands:
    - pip check
    - python -c "import pulp; assert pulp.LpSolverDefault, 'default solver not available'"
  requires:
    - pip

about:
  summary: |
    PuLP is an LP modeler written in python. PuLP can generate MPS or LP files
    and call GLPK, COIN CLP/CBC, CPLEX, and GUROBI to solve linear problems.
  home: https://github.com/coin-or/pulp
  license: MIT
  license_file: LICENSE
  doc_url: https://pythonhosted.org/PuLP/
  dev_url: https://github.com/coin-or/pulp
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - christopher-schroeder
    - venaturum
