{% set version = "2.1" %}

package:
  name: pulp
  version: {{ version }}

source:
  sha256: 76f9c9f984e6e407959545a556ce10c6cc0fdb0db820d627f0073ecf4f5c5c1b
  fn: PuLP-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/PuLP/PuLP-{{ version }}.tar.gz

build:
  entry_points:
    - pulptest = pulp:pulpTestAll
    - pulpdoctest = pulp:pulpDoctest
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyparsing >=2.0.1

test:
  commands:
    - pulptest --help
  imports:
    - pulp
    - pulp.solverdir

about:
  summary: |
    PuLP is an LP modeler written in python. PuLP can generate MPS or LP files
    and call GLPK, COIN CLP/CBC, CPLEX, and GUROBI to solve linear problems.
  home: https://github.com/coin-or/pulp
  license: MIT
  license_file: LICENSE
  doc_url: https://pythonhosted.org/PuLP/
  dev_url: https://github.com/coin-or/pulp
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - christopher-schroeder
