{% set name = "pulp" %}
{% set version = "2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PuLP-{{ version }}.tar.gz
  sha256: 9d8ecf532868cc31fa9ff59ee5d5b2049600c5c902c18c794a2bad677c1f92e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - amply >=0.1.2
    - python

test:
  imports:
    - pulp
    - pulp.solverdir
  commands:
    - pip check
  requires:
    - pip

about:
  summary: |
    PuLP is an LP modeler written in python. PuLP can generate MPS or LP files
    and call GLPK, COIN CLP/CBC, CPLEX, and GUROBI to solve linear problems.
  home: https://github.com/coin-or/pulp
  license: MIT
  license_file: LICENSE
  doc_url: https://pythonhosted.org/PuLP/
  dev_url: https://github.com/coin-or/pulp
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - christopher-schroeder
