schema_version: 1

context:
  version: "4.0.0"

package:
  name: pulp
  version: ${{ version }}

source:
  url: https://github.com/coin-or/pulp/archive/refs/tags/${{ version }}.tar.gz
  sha256: 88b09a0eb91e3def0c1c3918b17e3838a6bfa247b194453a4de382ce4c57e5f0
  patches:
    # https://github.com/coin-or/pulp/pull/950
    - patches/rust-build.patch

build:
  number: 0
  skip: match(python, "<3.12")
  script:
    # part of https://github.com/coin-or/pulp/pull/950
    - if: unix
      then: mv pulp/rust rust
      else: move pulp/rust rust
    - ${{ PYTHON }} -m pip install . -vv
    - cd rust && cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  python:
    entry_points:
      - pulptest = pulp.tests.run_tests:pulpTestAll

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python
    - orloge >=1.0.0
    - coin-or-cbc

tests:
  - python:
      imports:
        - pulp
      pip_check: true
  - script:
      - python -c "import pulp; assert pulp.LpSolverDefault, 'default solver not available'"
      - if: unix
        then: cd ${SP_DIR} && pulptest
        else: cd %SP_DIR% && pulptest

about:
  summary: |
    PuLP is an LP modeler written in python. PuLP can generate MPS or LP files
    and call GLPK, COIN CLP/CBC, CPLEX, and GUROBI to solve linear problems.
  license: MIT
  license_file:
    - LICENSE
    - rust/THIRDPARTY.yml
  homepage: https://github.com/coin-or/pulp
  repository: https://github.com/coin-or/pulp

extra:
  recipe-maintainers:
    - johanneskoester
    - christopher-schroeder
    - mgorny
