appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZOaUVZHPDOCnZkKTaLmLJC9hc3QS/2CRiI66pOf646ZIRgfrDV4YMuxk5LHXgcLlEPHaIEzE3RElHPzKwooWiYT8JwpGuOfwL+PAexHi+/Ob0YRLFnE7Cqi/bGDexsuK7emj/YdJkuLU3ZaMM2/URWyeuGv5/SYAO9GxNIxW+MkvmDI/vhxITNASJjUQhh6m45z61tjhaQLGGAPUVNVhaoQb2jRImePDxLj9AsfK4oN4tls8hdEkA0iEl+d3VwJnY4wgqmqHCpuzuGR3IwVFdClc4eY741REmEjW0pZjd7zCpnYB+zbAZeWDXJmTfEStnYmyTrQzVM6T1f+DSym/gjP++ws4jy9wO+s5ayf2Kff4VZ3V/gXsRQwFFJYgKNMrON8l/tfwhnQ0dGMEJc7PB1zqKhM7MwTHM7DEiiMtP8mEB+aNGgQED2VqWk8/Dn883v8ikZE0/Jr+FpYBK4EZeo9bGpAbD7LM4UZM4d1nSUH9xSXnl47N0BC/OGIhe/CCbGl0SE2jqif5J/4d3szPc9teKQC3Pn+YseDZVXXpOKABxbmECSDkRljHm5ymhdrQkVjwKKmZ6KyX81LPzn/uXKclaILdo00tkvCdlVURwUE5ZkfA/7hXUBYckNdG6FpaXK2MtTFuzD4EtwxH4UDx41riPKTcIYRjvImrbx6N8FQ=}
