bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
provider:
  linux_ppc64le: azure  
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
azure:
  store_build_artifacts: True
